# Generated by Django 3.2.18 on 2023-05-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcontrol', '0003_controllerdata_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controllerdata',
            options={'ordering': ['id'], 'verbose_name': 'Данные', 'verbose_name_plural': 'Данные'},
        ),
    ]
